name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci-main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Restore cached npm dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
            /home/runner/.cache/Cypress
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
      - name: Cache npm dependencies
        id: cache-dependencies-save
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
            /home/runner/.cache/Cypress
          key: ${{ steps.cache-dependencies-restore.outputs.cache-primary-key }}
      - uses: nrwl/nx-set-shas@v3
      - name: This line is needed for nx affected to work when CI is running on a PR
        if: ${{ github.ref  != 'refs/heads/main' }}
        run: git branch --track main origin/main
      - run: pnpm nx affected -t lint test build --parallel=3
      - run: pnpm nx affected -t e2e --parallel=1

      - name: Test nx uses remote Cache
        run: echo "[remote cache] found?"